//go:build linux

package aio

import "github.com/brickingsoft/rio/pkg/liburing"

func (op *Operation) Name() string {
	switch op.code {
	case liburing.OpNop:
		return "nop"
	case liburing.OpReadv:
		return "readv"
	case liburing.OpWritev:
		return "writev"
	case liburing.OpFsync:
		return "fsync"
	case liburing.OpReadFixed:
		return "read_fixed"
	case liburing.OpWriteFixed:
		return "write_fixed"
	case liburing.OpPollAdd:
		return "poll_add"
	case liburing.OpPollRemove:
		return "poll_remove"
	case liburing.OpSyncFileRange:
		return "sync_file_range"
	case liburing.OpSendmsg:
		return "sendmsg"
	case liburing.OpRecvmsg:
		return "recvmsg"
	case liburing.OpTimeout:
		return "timeout"
	case liburing.OpTimeoutRemove:
		return "timeout_remove"
	case liburing.OpAccept:
		return "accept"
	case liburing.OpAsyncCancel:
		return "async_cancel"
	case liburing.OpLinkTimeout:
		return "link_timeout"
	case liburing.OpConnect:
		return "connect"
	case liburing.OpFallocate:
		return "fallocate"
	case liburing.OpOpenat:
		return "openat"
	case liburing.OpClose:
		return "close"
	case liburing.OpFilesUpdate:
		return "files_update"
	case liburing.OpStatx:
		return "statx"
	case liburing.OpRead:
		return "read"
	case liburing.OpWrite:
		return "write"
	case liburing.OpFadvise:
		return "fadvise"
	case liburing.OpMadvise:
		return "madvise"
	case liburing.OpSend:
		return "send"
	case liburing.OpRecv:
		return "recv"
	case liburing.OpOpenat2:
		return "openat2"
	case liburing.OpEpollCtl:
		return "epollctl"
	case liburing.OpSplice:
		return "splice"
	case liburing.OpProvideBuffers:
		return "provide_buffers"
	case liburing.OpRemoveBuffers:
		return "remove_buffers"
	case liburing.OpTee:
		return "tee"
	case liburing.OpShutdown:
		return "shutdown"
	case liburing.OpRenameat:
		return "renameat"
	case liburing.OpUnlinkat:
		return "unlinkat"
	case liburing.OpMkdirat:
		return "mkdirat"
	case liburing.OpSymlinkat:
		return "symlinkat"
	case liburing.OpLinkat:
		return "linkat"
	case liburing.OpMsgRing:
		return "msgring"
	case liburing.OpFsetxattr:
		return "fsetxattr"
	case liburing.OpSetxattr:
		return "setxattr"
	case liburing.OpFgetxattr:
		return "fgetxattr"
	case liburing.OpGetxattr:
		return "getxattr"
	case liburing.OpSocket:
		return "socket"
	case liburing.OpUringCmd:
		return "uringcmd"
	case liburing.OpSendZC:
		return "sendzc"
	case liburing.OpSendMsgZC:
		return "sendmsgzc"
	case liburing.OpReadMultishot:
		return "read_multishot"
	case liburing.OpWaitId:
		return "wait_id"
	case liburing.OpFutexWait:
		return "futex_wait"
	case liburing.OpFutexWake:
		return "futex_wake"
	case liburing.OpFutexWaitv:
		return "futex_waitv"
	case liburing.OPFixedFdInstall:
		return "fixed_fd_install"
	case liburing.OpFtuncate:
		return "ftuncate"
	case liburing.OpBind:
		return "bind"
	case liburing.OpListen:
		return "listen"
	case liburing.OpRecvZC:
		return "recvzc"
	case liburing.OpEpollWait:
		return "epollwait"
	case liburing.OpReadvFixed:
		return "readv_fixed"
	case liburing.OpWritevFixed:
		return "writev_fixed"
	default:
		return "unknown"
	}
}
